name: Build and Deploy to Cloud Run

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    name: Build and Deploy to Cloud Run
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY_BASE64 }}

      - name: Decode service account key
        run: |
          echo "${{ secrets.GCP_SA_KEY_BASE64 }}" | base64 --decode > key.json
          gcloud auth activate-service-account --key-file=key.json
          gcloud config set project ${{ secrets.GCP_PROJECT_ID }}

      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker image
        run: |
          docker build -t hello-world:latest .
      
      - name: Tag Docker image
        run: |
          docker tag hello-world:latest ganshekar/hello-world:latest

      - name: Push Docker image to Docker Hub
        run: |
          docker push ganshekar/hello-world:latest

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy hello-world \
            --image docker.io/ganshekar/hello-world:latest \
            --region us-central1 \
            --platform managed \
            --allow-unauthenticated  # Modify as per your authentication needs
