name: Deploy to Cloud Run

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    name: Build and Deploy to Cloud Run
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        export_default_credentials: true

    - name: Build and push Docker image
      run: |
        docker build -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/my-react-app .
        docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/my-react-app

    - name: Deploy to Cloud Run
      run: |
        gcloud run deploy my-react-app --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/my-react-app --region us-central1 --platform managed
      - main  # Change this to your branch name if different

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v0.2.0
        with:
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          project_id: ds-ms-microservices  # Replace with your Google Cloud Project ID

      - name: Build and push Docker image
        run: |
         docker build -t gcr.io/ds-ms-microservices/rcganshekar/hello-world:latest .
          docker push gcr.io/ds-ms-microservices/rcganshekar/hello-world:latest

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy my-react-app \
            --image gcr.io/ds-ms-microservices/rcganshekar/hello-world:latest \
            --platform managed \
            --region us-central1 \
            --allow-unauthenticated
