name: Deploy to Cloud Run

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    name: Build and Deploy to Cloud Run
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true
          version: '357.0.0'  # Adjust the version as necessary

      - name: Authenticate Docker with Google Cloud
        run: |
          gcloud auth configure-docker

      - name: Debug environment
        run: |
          echo "Project ID: ${{ secrets.GCP_PROJECT_ID }}"
          gcloud auth list
          gcloud auth print-identity-token

      - name: Build and push Docker image
        run: |
          docker build -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/rcganshekar/hello-world:latest .
          docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/rcganshekar/hello-world:latest

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy my-react-app \
            --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/rcganshekar/hello-world:latest \
            --region us-central1 \
            --platform managed
