name: Build, Push to Docker Hub, and Deploy to Cloud Run

on:
  push:
    branches:
      - master

jobs:
  build-push-and-deploy:
    name: Build, Push to Docker Hub, and Deploy to Cloud Run
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure Docker credentials
        run: |
          echo '{"auths":{"https://index.docker.io/v1/":{"auth":"$(echo -n ${{ secrets.DOCKER_USERNAME }}:${{ secrets.DOCKER_PASSWORD }} | base64)"}}}' > /tmp/config.json
          mkdir -p ~/.docker
          mv /tmp/config.json ~/.docker/config.json

      - name: Build and Push Docker image
        env:
          IMAGE_TAG: latest  # Replace with your desired image tag
        run: |
          docker build -t ganshekar/hello-world:${IMAGE_TAG} .
          docker push ganshekar/hello-world:${IMAGE_TAG}

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY_BASE64 }}

      - name: Deploy to Cloud Run
        env:
          IMAGE_TAG: latest  # Use the same IMAGE_TAG as pushed to Docker Hub
        run: |
          gcloud run deploy hello-world \
            --image ganshekar/hello-world:${IMAGE_TAG} \
            --region us-central1 \
            --platform managed \
            --allow-unauthenticated
