name: Build and Deploy

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and Push Docker image
        env:
          IMAGE_TAG: latest
        run: |
          docker build -t ganshekar/hello-world:${IMAGE_TAG} .
          docker push ganshekar/hello-world:${IMAGE_TAG}
      
      - name: Rename Docker config file
        run: mv ~/.docker/config.json ~/.docker/config.json.old
      
      - name: Deploy to Cloud Run
        uses: google-github-actions/deploy-cloudrun@main
        with:
          service: hello-world  # Replace with your Cloud Run service name
          image: gcr.io/ds-ms-microservices/hello-world:${IMAGE_TAG}  # Replace with your image reference
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          region: us-central1
          args: --port=8080  # Adjust port if necessary
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GCP_SA_KEY }}
