name: Build and Deploy to Cloud Run

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    name: Build and Deploy to Cloud Run
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY_BASE64 }}

      - name: Authenticate Docker to Google Cloud
        run: |
          echo "${{ secrets.GCP_SA_KEY_BASE64 }}" | base64 --decode > key.json
          gcloud auth activate-service-account --key-file=key.json
          gcloud config set project ${{ secrets.GCP_PROJECT_ID }}
          gcloud auth configure-docker

      - name: Login to Docker Hub
        run: |
          echo ${{ secrets.DOCKER_PASSWORD }} | docker login --username ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Get current timestamp
        id: get-timestamp
        run: echo "TIMESTAMP=$(date +%Y%m%d%H%M%S)" >> $GITHUB_ENV

      - name: Build Docker image
        env:
          GIT_SHA: ${{ github.sha }}
          TIMESTAMP: ${{ env.TIMESTAMP }}
        run: |
          IMAGE_TAG=${GIT_SHA::7}-${TIMESTAMP}
          docker build -t ganshekar/hello-world:${IMAGE_TAG} .
          echo "IMAGE_TAG=${IMAGE_TAG}" >> $GITHUB_ENV

      - name: Push Docker image to Docker Hub
        env:
          IMAGE_TAG: ${{ env.IMAGE_TAG }}
        run: |
          docker push ganshekar/hello-world:${IMAGE_TAG}

      - name: Deploy to Cloud Run
        env:
          IMAGE_TAG: ${{ env.IMAGE_TAG }}
        run: |
          gcloud run deploy hello-world \
            --image ganshekar/hello-world:${IMAGE_TAG} \
            --region us-central1 \
            --platform managed \
            --allow-unauthenticated
