name: Build and Deploy to Cloud Run

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    name: Build and Deploy to Cloud Run
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY_BASE64 }}

      - name:  Print contents of service account key file
        run: |
          cat C:\\Keys\\ds-ms-microservices-c7375fc4c6b5.json  # Use double backslashes for file path in YAML

      - name: Authenticate with gcloud using local service account key
        run: |
          gcloud auth activate-service-account --key-file=C:\\Keys\\ds-ms-microservices-c7375fc4c6b5.json

      - name: Build and push Docker image to Container Registry
        run: |
          docker build -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/hello-world:latest .
          docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/hello-world:latest

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy hello-world \
            --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/hello-world:latest \
            --platform managed \
            --region us-central1
